import localFont from 'next/font/local'
import './globals.css'

import { MenuWrapper } from '@/context/menus'

const lato = localFont({
  src: [
    { path: './fonts/Lato-Thin.ttf', weight: '100' },
    { path: './fonts/Lato-Light.ttf', weight: '300' },
    { path: './fonts/Lato-Regular.ttf', weight: '400' },
    { path: './fonts/Lato-Bold.ttf', weight: '700' },
    { path: './fonts/Lato-Black.ttf', weight: '900' },
  ],
  variable: '--font-lato', // CSS varijabla koju možeš koristiti u stilu
})

export const metadata = {
  title: 'Zlatara Alex',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <MenuWrapper>
        <body className={`${lato.variable} antialiased`}>{children}</body>
      </MenuWrapper>
    </html>
  )
}
